version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: search-engine-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: searchengine
    volumes:
      - mongodb_data:/data/db
    networks:
      - search-engine-network

  elasticsearch:
    image: elasticsearch:7.17.15
    container_name: search-engine-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=search-engine-cluster
      - node.name=search-engine-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - search-engine-network

  kibana:
    image: kibana:7.17.15
    container_name: search-engine-kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - search-engine-network

volumes:
  mongodb_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  search-engine-network:
    driver: bridge 